### ISSUE TITLE
Build fails with "unstable feature" error in rkv dependency

### ISSUE THREAD

**Issue by kfogel** [phiresky/ripgrep-all#10]
I tried doing `cargo build` (of `master` at commit ef2e4ebf28f) and got this error:

```
  $ cargo build 
      Updating crates.io index
   Downloading crates ...
    Downloaded chrono v0.4.6
    Downloaded encoding_rs v0.8.17
    [...]
     Compiling zip v0.5.2
     Compiling serde_json v1.0.39
     Compiling rkv v0.9.6
  error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
     --> /home/kfogel/.cargo/registry/src/github.com-1ecc6299db9ec823/rkv-0.9.6/src/error.rs:166:11
      |
  166 | impl From<::std::num::TryFromIntError> for MigrateError {
      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
    --> /home/kfogel/.cargo/registry/src/github.com-1ecc6299db9ec823/rkv-0.9.6/src/migrate.rs:78:5
     |
  78 |     convert::TryFrom,
     |     ^^^^^^^^^^^^^^^^
  
  [...many more similar error lines...]
  
  error: aborting due to 12 previous errors
  
  For more information about this error, try `rustc --explain E0658`.
  error: Could not compile `rkv`.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  $ 
```

I don't know much Rust, but it looks like rkv is using an unstable feature ([rust bug 33417](https://github.com/rust-lang/rust/issues/33417) has more about it), and that since rga depends on rkv, this affects the rga build too.  I ran `rustc --explain E0658` and got some information about how to solve the problem -- presumably those solutions would have to be implemented upstream in rkv, if we wanted to solve this for everyone, or else I'd have either build a modified rkv locally *or* get the nightly version of `rustc` to do the build I just tried to do.

I'm not sure what ways might be available to solve this within rga.  Ideas welcome; like I said, I don't know Rust that well.

Anyway, this was all along the way to submitting a PR for `README.md` to add installation instructions.  I'll submit that PR, and then in its commentary mention this issue.

**Comment by phiresky** [comment]
It should actually build on Rust stable, in fact [the CI is checking that](https://travis-ci.org/phiresky/ripgrep-all). Can you say which Rust version you are on? (`rustc --version`). And if you are not on 1.35, use `rustup update` to update.

**Comment by kfogel** [comment]
rustc 1.32.0

Thanks; I'll try the update.  I was just using whatever the latest rustc in Debian GNU/Linux 'testing' distro is -- which is apparently not quite up-to-date with upstream stable.

**Comment by hldh214** [comment]
i meet the same issue and solved with `rustup install nightly`

**Comment by anowlcalledjosh** [comment]
You don't need nightly to solve this, [just Rust 1.34 or higher](https://github.com/rust-lang/rust/issues/33417#issuecomment-499176729).

**Comment by phiresky** [comment]
I've modified the readme to make it clearer you need 1.35+. I don't think I want to support older Rust versions

**Comment by kfogel** [comment]
Thanks everyone for the followups.  I'll get 1.35 or higher and use that.
