### ISSUE TITLE
How to set a file type for search?

### ISSUE THREAD

**Issue by cryoguy** [phiresky/ripgrep-all#100]
I could not seem to find the answer.  How to set a file type for search? like the `-torg` for org files in `rg`.

**Comment by phiresky** [comment]
It should work the same as for rg. Both `-t` as well as `-g`

**Comment by cryoguy** [comment]
is there a way to implement this after integration with fzf?

**Comment by phiresky** [comment]
Yeah, you can adjust the script from the readme to pass `-tfoo` to rga. or maybe make it use "$@" instead of "$1"

**Comment by cryoguy** [comment]
Thanks for your prompt reply!  Using "$@" results in nothing in results when passing, say `-torg` to it.  I think it is due to the `--phony -q "$1"`.  I wanted to make file type optional. So if I do not pass the arguments, it will just fall back to full search. But I am not efficient in shell-script enough to implement this.
