### ISSUE TITLE
Please add a way to specify the cache directory

### ISSUE THREAD

**Issue by bionicles** [phiresky/ripgrep-all#102]
Dear @phiresky,

Thank you for making this! It is super cool.

I'm using this on a security project and figure the cache could leak information about the stuff being searched. If I could pass a flag like `--cache-dir` to specify the directory then I could put it into the same sandbox as the data and delete everything as soon as a search is completed. I realize I could just delete the cache when I delete the data, but I'd ideally like to subject that to the same security controls as the other data...

one question: how can we specify a cache directory? 

Bion

**Comment by bionicles** [comment]
Also: how do you use `rga-fzf.rs` ?

**Comment by phiresky** [comment]
You should be able to set `XDG_CACHE_HOME` to change the cache dir. If you're only searching once you can also just use `--rga-no-cache`.

`rga-fzf.rs` will only work in the next (yet unreleased) version. For now you should use the similar `rga-fzf()` shell function from the README
