### ISSUE TITLE
how to install rga on ubuntu?

### ISSUE THREAD

**Issue by pleabargain** [phiresky/ripgrep-all#107]
I downloaded the binary file from
`https://github.com/phiresky/ripgrep-all/releases/tag/v0.9.6` 
I checked 
`file *`
and got
`rga:         ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=45d1518de4876122173fd942bd11216edc02e107, stripped`
but that doesn't tell me if it's a `.bin` or `.run`

Please assist. How do I install rga on Ubuntu 20?

thank you!

**Comment by phiresky** [comment]
You downloaded the wrong binary, get the x86_64 one

**Comment by pleabargain** [comment]
I downloaded  the x86
I ran `chmod + x rga`

but ./rga 
only works in the directory where I ran 
`chmod + x rga`

I can only search in the folder where `rga` is sitting e.g.
`./rga 'concise' README.md `
works
but only in that directory.

Please assist.

thank you
