### ISSUE TITLE
Request: include the contents of "doc" in the released archive

### ISSUE THREAD

**Issue by m040601** [phiresky/ripgrep-all#109]
In adition to a normal package that pulls the source code and compiles it, we have another alternative to install rga in Arch Linux. This other package recipe (PKGBUILD)  simply pulls your released archive containing the binary, and copies it, without the need for installing go and compiling.
Very usefull and practical. But, we only get what you put in the release archive.

You release a tar.gz containing,

```

└── ripgrep_all-v0.9.6-x86_64-unknown-linux-musl
    ├── doc
    │   └── CHANGELOG.md
    ├── LICENSE.md
    ├── README.md
    ├── rga
    └── rga-preproc


```

But on the repo there is  a folder "doc", containing much more,

```


doc
├── Custom adapters.md
├── demodir.png
├── notes.md
├── rga-fzf.gif
└── update-readme.sh


```

Please include its full contents. These "notes.md" et all are extremely usefull.
Thanks in advance.

**Comment by Zhomart** [comment]
Agree, what's `rga-preproc` ?

**Comment by phiresky** [comment]
Really by now the main useful documentation is 

1. the readme
2. the `rga --help` output
3. the default config and config schema which is auto-generated and written to ~/.config
4. the github discussions and wiki pages (which can't really be included)

So i don't think it would be very useful to add the kinda random files in /doc. The main thing that could be improved is to allow a `--help` flag on rga-preproc but that's a different thing.
