### ISSUE TITLE
text searching through gpg encrypted documents?

### ISSUE THREAD

**Issue by dariusjonda** [phiresky/ripgrep-all#119]
first of all thank you for this amazing tool!  

After utilizing it for a few days I was wondering if anyone found a solution to use `rga` to search through gpg encrypted files?  
I imagine this might be quite handy, especially when dealing with a lot of gpg encrypted documents (notes, logs etc) on a regular basis ...

thanks in advance!

**Comment by lafrenierejm** [comment]
It feels like this would be super tricky to handle in a reasonable way.

1. `rga` would need to decrypt the file during the initial search. If the user doesn't have a GPG agent configured or if they have a low enough retention period, they would potentially get prompted multiple times within a single `rga` invocation.
1. `rga` would need to encrypt the cache results with the same GPG key(s) as the original file. Not doing this would result in (some variant of) the cleartext existing on disk, which would defeat the purpose of the original encryption.
   1. Those encrypted cache files would be unlocked each time `rga` runs. This has the same downside of potentially prompting the user multiple times.
   1. `rga` would need to create a separate cache file per unique GPG key. If someone were to use multiple GPG keys, this would further reduce `rga`'s performance by requiring decrypting and scanning multiple cache files.

**Comment by phiresky** [comment]
I don't think this is reasonable to be in scope of rga. It can be accomplished with custom adapters though
