### ISSUE TITLE
cargo install ripgrep_all  fails

### ISSUE THREAD

**Issue by raichuAK** [phiresky/ripgrep-all#12]
Cargo install ripgrep_all fails with below error. 
Machine is linux Rhel 7
cargo 1.34.0 

Do let me know if you need more details.

error[E0161]: cannot move a value of type dyn for<'r> std::ops::FnOnce(&'r [u8]) -> std::result::Result<(), failure::error::Error>: the size of dyn for<'r> std::ops::FnOnce(&'r [u8]) -> std::result::Result<(), failure::error::Error> cannot be statically determined
  --> /home/<My_home>/.cargo/registry/src/github.com-1ecc6299db9ec823/ripgrep_all-0.9.1/src/preproc_cache.rs:77:17
   |
77 |                 callback(cached)?;
   |                 ^^^^^^^^

error[E0161]: cannot move a value of type dyn std::ops::FnOnce() -> std::result::Result<std::option::Option<std::vec::Vec<u8>>, failure::error::Error>: the size of dyn std::ops::FnOnce() -> std::result::Result<std::option::Option<std::vec::Vec<u8>>, failure::error::Error> cannot be statically determined
  --> /home/<My_home>/.cargo/registry/src/github.com-1ecc6299db9ec823/ripgrep_all-0.9.1/src/preproc_cache.rs:83:36
   |
83 |                 if let Some(got) = runner()? {
   |                                    ^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0161`.
error: failed to compile `ripgrep_all v0.9.1`, intermediate artifacts can be found at `/tmp/cargo-installyxoOOy`

Caused by:
  Could not compile `ripgrep_all`.

**Comment by phiresky** [comment]
Can you try compiling with Rust 1.35 stable?

**Comment by raichuAK** [comment]
> Can you try compiling with Rust 1.35 stable?

Yes it works after upgrading.
Thanks

**Comment by phiresky** [comment]
Nice. I'll close this since I don't think I want to support older Rust versions (even if e.g. debian probably has older versions packaged)
