### ISSUE TITLE
Support Powerpoint

### ISSUE THREAD

**Issue by Immortalin** [phiresky/ripgrep-all#124]
https://www.loc.gov/preservation/digital/formats/fdd/fdd000399.shtml

**Comment by Mstrodl** [comment]
I've been using this:
```
soffice --headless --convert-to pdf *.ppt *.pptx && rm *.ppt *.pptx
```

**Comment by lafrenierejm** [comment]
This seems like a duplicate of <https://github.com/phiresky/ripgrep-all/issues/69>.

**Comment by Konfekt** [comment]
Might https://github.com/phiresky/ripgrep-all/discussions/199 be of help?

**Comment by phiresky** [comment]
Please see @Konfekt s custom adapter #199
