### ISSUE TITLE
Feature request: Use `ugrep` as the backend in place of `ripgrep`.

### ISSUE THREAD

**Issue by hongyi-zhao** [phiresky/ripgrep-all#126]
Currently,  [`ripgrep-all`](https://github.com/phiresky/ripgrep-all), a.k.a, `rga` uses the awesome [ripgrep](https://github.com/BurntSushi/ripgrep) as its backend. But I also noticed that there is another similar but even powerful tool [`ugrep`](https://github.com/Genivia/ugrep), as described [here](https://github.com/Genivia/ugrep#readme):

>  Ultra fast with new match algorithms and features beating grep, ripgrep, silver searcher, ack, sift, etc.

So, I think that it would be great if `rga` can also use `ugrep` as an alternative backend.

Regards,
HZ

**Comment by phiresky** [comment]
It seems like `ug` has a feature `ug+` that "competes" with rga in that it also searches pdf files and archives. I don't think it would be too useful to reimplement that functionality?
