### ISSUE TITLE
Doesn't follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by shufuwa** [phiresky/ripgrep-all#129]
rga stores cache in ~/.cache instead of $XDG_CACHE_HOME/rga/

**Comment by edd255** [comment]
Currently, the project uses the _directories_next_-crate which seems to follow the XDG Base Directory Specification. However, the last release was from May 2020. phiresky plans to release a beta version soon, as he explained in #146.

**Comment by lafrenierejm** [comment]
To expand on @edd255's answer: If you want a version that supports the XDG directory spec, you can grab [v1.0.0-alpha.5](https://github.com/phiresky/ripgrep-all/releases/tag/v1.0.0-alpha.5) (the latest alpha as of this writing).

**Comment by phiresky** [comment]
fixed in 0.10
