### ISSUE TITLE
ripgrep-all error not found xdg-open on macOS

### ISSUE THREAD

**Issue by ciscohack** [phiresky/ripgrep-all#130]
hello Experts,

first thanks for such a great tool. I am running the ripgrep-all tool on my macOS 12.3 and I noticed when I run the command rga-fzf  search to file works fine but when I hit enter to open I get below error. What I know xdg-open tool is only available on Linux device not on macOS. how can we fix it as we are not able to open the file shown in the search result? Hoping you will fix it 

![image](https://user-images.githubusercontent.com/11479557/163600960-17a70244-e481-4feb-8640-a1f00ee7a4af.png)

**Comment by ciscohack** [comment]
Hello Experts, Any comment on this issue?

**Comment by brachkow** [comment]
Replace `xdg-open` with `open`

**Comment by ciscohack** [comment]
Thanks
