### ISSUE TITLE
rga-fzf returning different results than rga

### ISSUE THREAD

**Issue by tmceld** [phiresky/ripgrep-all#135]
version: ripgrep-all 0.9.6
macos 11.6.6
zsh 5.8

Great tool, and just what i was looking for.  I noticed that after adding some books (epub) to my folder that a certain search term will return matches when used with `rga 'henrik larsson'` but not with `rga-fzf 'henrik larsson'`

I _suspect_ that this is due to caching, partly because the books that contain this term, were added after the initial run, but cannot be sure.

**Comment by phiresky** [comment]
Please try again with 0.10 and if not attach a reproducible example
