### ISSUE TITLE
The docx, doc, and odt files not recoginzed by rga

### ISSUE THREAD

**Issue by adamkvitek** [phiresky/ripgrep-all#136]
When searching for .docx, .doc, and .odt files - rga returned "Unrecognized file type" on Windows 10.

Using for example:
```
rga "La Source" -t=docx
```
Or:
```
rga "La Source" -t docx
```

Returned:
```
unrecognized file type:docx
```

**Comment by Shreyas-Murali** [comment]
`rga -g *.docx" pattern` seems to work for me

**Comment by phiresky** [comment]
The `-t` parameter is not supported. `-g` should work fine
