### ISSUE TITLE
epub not reconized

### ISSUE THREAD

**Issue by ecovisiones** [phiresky/ripgrep-all#137]
I have the next problem whuen I use rga:
~$ rga -s 'Losartan'
Escritorio/receta.txt
Amlodipino 5mg 1 caja, Alopurinol 300mg 1 caja, Carvedilol 12,5mg 2 cajas, Losartan 50 mg 2 cajas, Hipoglucin 1000mg 1 caja 60 comprimidos, Amioradona 200mg 2 cajas, Xarelto 20mg 1 caja, Atorvastatina 20mg 1 caja.
Zotero/storage/Y5TFHDQX/Aquelarre.epub: preprocessor command failed: '"/home/jorge/.local/bin/rga-preproc" "Zotero/storage/Y5TFHDQX/Aquelarre.epub"': 
-------------------------------------------------------------------------------
adapter: pandoc
Couldn't extract ePub file
Error: subprocess failed: ExitStatus(ExitStatus(16384))
-------------------------------------------------------------------------------

**Comment by lafrenierejm** [comment]
@ecovisiones Can you share `Aquelarre.epub` here as well as the version of `pandoc` you're using?

**Comment by phiresky** [comment]
No example and missing info
