### ISSUE TITLE
[FEATURE] replace pandoc with epub2txt2 for Epub search

### ISSUE THREAD

**Issue by mindreframer** [phiresky/ripgrep-all#138]
First - what an awesome project! It really makes searching of huge document libraries possible. 

Currently I have a lot of issues with Epub parsing, pandoc hangs forever with 100% CPU when parsing some EPUB files, sometimes bigger, but sometimes also on smaller ones. Currently I don't have a good workaround for this. 

I tried parsing those files that cause issues with https://github.com/kevinboone/epub2txt2 and it returns the content instantly. 
Also, judging by the amount of issues here with EPUB parsing, this could be a a good solution for many other issues. 

Please consider allowing to use epub2txt2 as backend for EPUB extraction. 

Thanks!

**Comment by phiresky** [comment]
in the next version (when i or someone finally manages to make it work), the preprocessors will be configurable per file type

**Comment by mindreframer** [comment]
@phiresky OMG, that would be awesome! Any ideas, how the configuration would look like? E.g when I'm overriding Docx preprocessor, how would I specify it?

**Comment by phiresky** [comment]
Starting with 1.0.0, it's possible to add custom adapters [via the config file](https://github.com/phiresky/ripgrep-all/wiki). If someone has a good suggestion for a file type please post it in [show-your-adapter](https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter)
