### ISSUE TITLE
Errors not showing in stderr

### ISSUE THREAD

**Issue by SterlingHooten** [phiresky/ripgrep-all#139]
Error codes in rg can indicate whether a match was found at all, but when the same query is used with rga the error isn't passed to stderr. Am I missing something obvious?

I'm trying to get rga to stop searching after a match is found, exit with a '0' to stderr, otherwise exiting with a '1' to stderr as is the behavior in rg.

Thanks!
Sterling

**Comment by phiresky** [comment]
fixed in 0.10.5
