### ISSUE TITLE
common ebook formats

### ISSUE THREAD

**Issue by guaka** [phiresky/ripgrep-all#14]
nice to have: support for `epub` `mobi` `fb2` and other ebook formats

**Comment by phiresky** [comment]
Good idea. epub and fb2 are actually already supported! But mobi is a bit harder. I could write an adapter for `ebook-convert` from calibre which should know pretty much everything, but that tool is veeery slow (e.g. `ebook-convert wasteland.mobi wasteland.txt`)

**Comment by DeftNerd** [comment]
https://wiki.mobileread.com/wiki/MOBI has some good information about the Mobi file format. Of note, https://github.com/kevinhendricks/KindleUnpack is a Python script that looks particularly useful. 

> KindleUnpack extracts MOBI or AZW (Amazon Kindle) source files from the final compiled database format. The filenames used for the source files are not necessarily the same as those that were originally used to create the database, as this information is not preserved in the database, but an unpacked set of files should be able to be used to recreate the same database using the standard MOBI or Kindle generating tools.
> 
> For KF8 files and combined Mobipocket and KF8 files built by KindleGen, it can also produce separated Mobipocket and KF8 files, as well as the original source files if those have been included in the eBook. Additionally, for KF8 files it can produce an 'ePub', though if the HTML isn't compliant with ePub standards, the 'ePub' won't be either.
> 
> For Amazon's .AZW4 files, it will extract the PDF that's been wrapped up in Amazon's .AZW4 file format.

**Comment by Kristinita** [comment]
**Type: Statistics** 📙

### 1. About

I'm Russian Jeopardy player. I have [**big list of books in all branches of knowledge**](https://kristinita.netlify.app/special/%D0%BF%D0%BE%D0%BB%D0%BD%D0%B0%D1%8F-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F). I think, that it can be regarded as a “[**representative sample**](https://www.statisticssolutions.com/what-is-a-representative-sample/)”, which formats are popular for Russian ebooks.

### 2. Table

*(The data in this table are as of 17 May 2020. Sometimes I add books to my list, so data will be different in the future.)*

I selected formats, that [**not supported by ripgrep-all**](https://github.com/phiresky/ripgrep-all#available-adapters) in 17 May 2020 and supported by [**Calibre `ebook-convert`**](https://manual.calibre-ebook.com/generated/en/ebook-convert.html).

|Format|Number of books|Percentage of total books|
|---|---|---|
|**All**|**1858**|**100**|
|DjVu|434|23,4|
|Doc|43|2,3|
|RTF|14|0,7|
|CHM|5|0,3|

As can be seen, [**DjVu supporting**](https://github.com/phiresky/ripgrep-all/issues/38) have a high priority for peoples, that works with ebooks.

Thanks.

**Comment by phiresky** [comment]
More stats on the libgen fiction data (2M books :p):

```sql
select lower(extension), count(*) as count from main group by lower(extension) order by count desc
```


lower(extension) | count
-- | --
epub | 1202092
pdf | 256240
mobi | 235953
rar | 117347
lit | 64659
txt | 57003
rtf | 56601
doc | 51285
azw3 | 47813
html | 24270
zip | 21306
htm | 20965
pdb | 11734
lrf | 10434
prc | 4977
cbz | 3954
htmlz | 3904
docx | 3083
fb2 | 2723
cbr | 2295
azw | 1583

**Comment by Kristinita** [comment]
**Type: Question** ❓

@phiresky, could you describe in details how you received this data? No DjVu (!), no CHM — it strange.

Thanks.

**Comment by phiresky** [comment]
@Kristinita 

Probably can't link it directly, but it's from the libgen mysql meta database dumps (should be able to find it with google). It could by that it just doesn't contain Djvu / chm because they don't allow uploading that kind of file (not sure why they would allow all that other crap then).

**Comment by phiresky** [comment]
Starting with 1.0.0, it's possible to add custom adapters [via the config file](https://github.com/phiresky/ripgrep-all/wiki). If someone has a good suggestion for a file type please post it in [show-your-adapter](https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter)
