### ISSUE TITLE
Searching encrypted files

### ISSUE THREAD

**Issue by dideler** [phiresky/ripgrep-all#140]
I have some password protected PDF files that I'd like to search with rga. How do I specify the password?

More general, is it possible to pass options to the underlying adapters on invocation?

**Comment by the-solipsist** [comment]
`pdfgrep` has the option `--password` to search through password-protected files. This is very helpful, e.g., if you have a number of PDFs from your bank which you want to search through, all with the same password. It'd be great if `ripgrep-all` got a similar feature.

**Comment by phiresky** [comment]
I think this would be out of scope for rga. You can create a custom adapter though. pdftotext seems to have -upw and -opw parameters. If you do, create a post in https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter
