### ISSUE TITLE
is there any adaptor which supports vsdx(visio) file?

### ISSUE THREAD

**Issue by zhuzhzh** [phiresky/ripgrep-all#141]
I hope rga can search visio file as well. but I didn't find any adaptor for it.

**Comment by phiresky** [comment]
Starting with 1.0.0, it's possible to add custom adapters [via the config file](https://github.com/phiresky/ripgrep-all/wiki). If someone has a good suggestion for a file type please post it in [show-your-adapter](https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter)
