### ISSUE TITLE
is too many time not update

### ISSUE THREAD

**Issue by newyorkthink** [phiresky/ripgrep-all#145]
![image](https://user-images.githubusercontent.com/87791643/203872814-30c36294-2331-4538-9cb7-01f6e4923e23.png)

the latest version is 2020, 
2022 not update?

**Comment by rickhg12hs** [comment]
Ref #144

**Comment by newyorkthink** [comment]
> Ref #144

oh no ：（

how can fix

anyone can fix it

**Comment by phiresky** [comment]
I've created an issue with the current state of the project plus where help is needed here: https://github.com/phiresky/ripgrep-all/issues/146
