### ISSUE TITLE
option not to print filenames being processed

### ISSUE THREAD

**Issue by daniejstriata** [phiresky/ripgrep-all#154]
When I use rga in a loop I'm already printing the filename if there was a match but because rga is writing out each filename it is processing and my match is JSON I need to cut of the filename with sed so not to break the json.

```
/home/user1/backup_2022-10-06_04-22-45_SD.zip
backup.json: [{"id": "376a3caa7ce1b08a804bd19f485c04f7"
```
I use sed to delete the filename inside the zip that contains the match

` sed -e 's/\backup.json:// '`

now rga output first line to contain the filename and the first bit of the json:
`/home/user1/backup_2022-10-06_04-22-45_SD.zip:  [{"id": "376a3caa7ce1b08a804bd19f485c04f7`

Would it not be neater if `rga` has an option to print only the matched text without printing the matched filename inside the ZIP and the ZIP's name.

**Comment by phiresky** [comment]
0.10.4 adds a flag --rga-no-prefix-filenames that implements this
