### ISSUE TITLE
rga-preproc fails when calling pandoc on .docx files (but probably other file types that require pandoc too)

### ISSUE THREAD

**Issue by gbstan** [phiresky/ripgrep-all#155]
It seems that calls to rga-preproc is incompatible with the current version of pandoc.

When calling rga on a folder containing .docx files, this is the typical error that occurs for .docx files:
```
... preprocessor command failed: '"/usr/local/bin/rga-preproc ...:
--atx-header adapter: pandoc
Unknown option --atx-headers.
Try pandoc --help for more information.
Error: subprocess failed: ExitStatus(unix_wait_status(1536))
```

On some .docx files the error code is different:

```
adapter: pandoc
Unknown option --atx-headers.
Try pandoc --help for more information.
Error: Broken pipe (os error 32)
```

Here are the version numbers:
ripgrep-all 0.9.6

pandoc 3.0.1
Features: +server +lua
Scripting engine: Lua 5.4

**Comment by keiichiiownsu12** [comment]
Looks like they made a fix [back in 2021](https://github.com/phiresky/ripgrep-all/commit/020000cc77d0d63c5a7b2871e6f22550b4dbc1a0#diff-2ed052dd4f13ac4841c1e3377b4c100faa9330c26d7ccbc30f971f3f87d9e30cR92); however, they have not released a new stable version since 2020. You'll probably need to compile from source.

**Comment by lkyhfx** [comment]
pandoc 3.0 has removed deprecated `--atx-headers` option, use version before 3.0 instead.

**Comment by akshayshedbalkar** [comment]
This has broken an important workflow at work :( Compiling from source did not help. cargo install --locked ripgrep_all installs v0.9.6. Is it possible to install a newer version from source?

**Comment by gbstan** [comment]
Could a new stable version be released? From the comments above it seems a version that fixes exists but hasn't been made available.

**Comment by tddschn** [comment]
> Could a new stable version be released? From the comments above it seems a version that fixes exists but hasn't been made available.

@phiresky Could you please release a new version with a fix?
