### ISSUE TITLE
Wrong page numbers with latest git version

### ISSUE THREAD

**Issue by vejkse** [phiresky/ripgrep-all#157]
I just compiled the current state of the code (commit c089e44), hoping to get correct page numbers for PDF files, even with textless pages, since this issue has been marked as closed: https://github.com/phiresky/ripgrep-all/issues/106

But now, even for files without any textless page, almost all page numbers are wrong, and by a lot.   I join an excerpt of a 19th century book, if I run `rga quis` on that book, I get results going up to page 19 (even though there is only 10 pages).  Here’s an analysis of the results:

- page 2 (correct)
- page 3 instead of page 2
- twice page 5 instead of page 3
- twice page 7 instead of page 4
- page 9 instead of page 5
- page 12 instead of page 7
- page 13 instead of page 7
- page 14 instead of page 8
- thrice page 15 instead of page 8
- page 17 instead of page 9
- page 18 instead of page 10
- thrice page 19 instead of page 10

[Digestorum seu pandectarum, liber  3. Digeste ou pandectes, livre  3-x1.pdf](https://github.com/phiresky/ripgrep-all/files/10686840/Digestorum.seu.pandectarum.liber.3.Digeste.ou.pandectes.livre.3-x1.pdf)

This file is not a specially chosen one, it’s the typical behaviour, as far I can tell.

**Comment by phiresky** [comment]
Thanks for the report and example file. This is probably related to the new postproc_pagebreaks function from #150 by @lafrenierejm or my modifications after that merge.

**Comment by phiresky** [comment]
This should be fixed in the latest master version. Please let me know if it persists

**Comment by vejkse** [comment]
Thank you! It gives the right page with all the files at tried.  (At first it didn’t, but this was due to an old cache I had to delete.)
