### ISSUE TITLE
Could this search in EXIF/PNG info texts

### ISSUE THREAD

**Issue by space-nuko** [phiresky/ripgrep-all#160]
Would be very useful to search through PNGs with embedded `iTXt` chunks. Stable diffusion webui saves them in a chunk with the name "parameters"

**Comment by phiresky** [comment]
Sure, shouldn't be hard to build if someone wants to take a stab. Is this data part of EXIF or no? If it is, using exiftool as an external integration should work well. I couldn't quickly find an example image.

**Comment by space-nuko** [comment]
Here is an example, you can use something like TweakPNG to view the PNG info. The data isn't EXIF actually, it's a custom PNG text chunk with the name `parameters`.

![](https://majinai.art/i/BlqXR1v.png)

**Comment by phiresky** [comment]
Added in 1.0.0-alpha.4

**Comment by phiresky** [comment]
Starting with 1.0.0, it's possible to add custom adapters [via the config file](https://github.com/phiresky/ripgrep-all/wiki). If someone has a good suggestion for a file type please post it in [show-your-adapter](https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter)

exif support should be easy by just using `exiftool -`
