### ISSUE TITLE
adapter: pandoc Error: subprocess failed: ExitStatus(unix_wait_status(16384))

### ISSUE THREAD

**Issue by blueray453** [phiresky/ripgrep-all#161]
Hi, I am Using Zorin OS. 

The command I used is

`rga -i "Content Coupling|scope of control|fan-in|fanin|afferent|Functional cohesion" .`

The error I am getting is:

```
adapter: pandoc
Couldn't extract ePub file
Error: subprocess failed: ExitStatus(unix_wait_status(16384))
```

**Comment by phiresky** [comment]
please attach an example file

**Comment by blueray453** [comment]
Sorry, I can not reproduce. I tried. I Think it has cached the files.

**Comment by blueray453** [comment]
Found one. Can not attach epub so compressed it.

[Software Design X-Rays Fix Technical Debt with Behavioral Code Analysis by Adam Tornhill.zip](https://github.com/phiresky/ripgrep-all/files/10842355/Software.Design.X-Rays.Fix.Technical.Debt.with.Behavioral.Code.Analysis.by.Adam.Tornhill.zip)

**Comment by phiresky** [comment]
Thanks. I've opened an issue upstream in pandoc: https://github.com/jgm/pandoc/issues/8663

We could maybe also try switching to a different parser for epub (maybe [epub-rs](https://github.com/danigm/epub-rs)). That might have other advantages (e.g. performance) but also disadvantages (more effort, less stable)

**Comment by lafrenierejm** [comment]
> Thanks. I've opened an issue upstream in pandoc: https://github.com/jgm/zip-archive/issues/63

Looks like that bug has been fixed upstream in pandoc's dependency, and then pulled into pandoc on [2023-03-04](https://github.com/jgm/pandoc/commit/b40001e38cc374ced7b864df5b9c26c1734773fe). Pandoc [3.1.1](https://github.com/jgm/pandoc/releases/tag/3.1.1) was the first release to include the fix.

**Comment by phiresky** [comment]
Thanks. Should be fixed then
