### ISSUE TITLE
Make it available on conda-forge

### ISSUE THREAD

**Issue by jerryc05** [phiresky/ripgrep-all#163]
Just wondering, it is possible to publish this tool to conda-forge just like ripgrep did (https://github.com/conda-forge/ripgrep-feedstock)? That would be very helpful!

**Comment by phiresky** [comment]
conda-forge packages are usually maintained by third parties. It would be possible to add ripgrep-all to conda-forge, but I'm not interested in doing or maintaining that myself. Someone else could step up. It would not be an officially supported installation method though.
