### ISSUE TITLE
No progress when searching with pdfpages adapter

### ISSUE THREAD

**Issue by hobofan** [phiresky/ripgrep-all#17]
I wanted to try the pdfpages + tesseract search, but it seems that it hangs every time I try to use the `pdfpages` adapter via the `--rga-adapters=+pdfpages,tesseract` flag.

Output without adapters (hit in last line):
```
RUST_LOG=debug rga Peroxid ./AAC-Stunde-14.pdf
[2019-06-20T11:55:57Z DEBUG ripgrep_all::args] our_args: ["rga"]
[2019-06-20T11:55:57Z DEBUG ripgrep_all::args] RGA_CONFIG={}
[2019-06-20T11:55:57Z DEBUG ripgrep_all::args] passthrough_args: ["Peroxid", "./AAC-Stunde-14.pdf"]
[2019-06-20T11:55:57Z DEBUG ripgrep_all::adapters] Chosen adapters: ffmpeg,pandoc,poppler,zip,decompress,tar,sqlite
Page 28:     b) O fast immer -2 (Ausnahme: Peroxide)
```

Output with adapters (process just hangs and doesn't exit on its own):
```
RUST_LOG=debug rga Peroxid ./AAC-Stunde-14.pdf --rga-adapters=+pdfpages,tesseract
[2019-06-20T11:57:28Z DEBUG ripgrep_all::args] our_args: ["rga", "--rga-adapters=+pdfpages,tesseract"]
[2019-06-20T11:57:28Z DEBUG ripgrep_all::args] RGA_CONFIG={"adapters":["+pdfpages","tesseract"]}
[2019-06-20T11:57:28Z DEBUG ripgrep_all::args] passthrough_args: ["Peroxid", "./AAC-Stunde-14.pdf"]
[2019-06-20T11:57:28Z DEBUG ripgrep_all::adapters] Chosen adapters: tesseract,pdfpages,ffmpeg,pandoc,poppler,zip,decompress,tar,sqlite
```

Just let me know if there is any more info you need!

**Comment by phiresky** [comment]
Can you try with `-j1`? I've had a weird problem wherer if multiple tesseract processes are running they seem to be much slower.

Also try running

`RUST_LOG=debug rga-preproc --rga-adapters=+pdfpages,tesseract ./AAC-Stunde-14.pdf` 

it should show some more detail

**Comment by hobofan** [comment]
`-j1` doesn't seem to change anything, assuming that this way of specifying the flag is correct:
```
RUST_LOG=debug rga -j1 Peroxid ./AAC-Stunde-14.pdf --rga-adapters=+pdfpages,tesseract -j1
```

I forgot to mention in the original post that I get the same behaviour if I only specify `pdfpages`, so I guess `tesseract` is not the problem here.

-----

Running with `rga-preproc` did show me some progress, and it did finally work! However with 2-3 secs per page/image `pdfpages` was much slower than I expected.

Thanks for the help!

**Comment by hobofan** [comment]
@phiresky Given that poppler is already a dependency, I think this could be optimized without too much effort by switching away from `convert`. I've had good success with poppler + cairo in the past.

Here is the code of a small program I used in the past to convert a pdf into pngs (which converts the same PDF ~20 times as fast):

```rust
use std::fs::File;

fn main() {
    let args = std::env::args().collect::<Vec<_>>();
    let in_path = &args[1];

    let document = poppler::PopplerDocument::new_from_file(in_path, "").unwrap();
    println!("Pages: {}", document.get_n_pages());
    let n_pages = document.get_n_pages();
    for page_i in 0..n_pages {
        let page = document.get_page(page_i).unwrap();

        let image_surface = cairo::ImageSurface::create(cairo::Format::A8, 612, 792).unwrap();
        let mut context = cairo::Context::new(&image_surface);

        page.render(&mut context);

        let mut file = File::create(format!("./output/{}.png", page_i)).unwrap();
        image_surface.write_to_png(&mut file).unwrap();
    }
}
```

**Comment by phiresky** [comment]
Kind of weird that it's so slow considering it also uses cairo as far as i know.. though your example has a very low resolution. But thanks for the code! Yeah, would be a good idea to use that library.. but it probably doesn't work on Windows (had multiple problems getting poppler to run on Windows as is). Also looks like the API for getting text (`poppler_page_get_text`) is pretty simplistic so it might not be enough to get the text in a somewhat formatted way.

**Comment by phiresky** [comment]
As a reference, I currently render the pdf at 300 DPI (hardcoded), which is 2480 pixels x 3508 pixels on an A4 page
