### ISSUE TITLE
Can't disable adapters

### ISSUE THREAD

**Issue by runxel** [phiresky/ripgrep-all#183]
**Describe the bug**
Trying to disable adapters with `--rga-adapters=-zip,sqlite` does not work.
Next search will still have .zip's being searched...
(not helpful at all, it will just spit a lot of errors like:)
```log
adapter: zip
Error: Unsupported Zip archive: The file length is not available in the local header
```

**Operating System and Version**
MacOS 13.5.2

**Output of `rga --version`**
ripgrep-all 0.9.6

**Comment by phiresky** [comment]
It seems to work for me on 1.0.0-alpha. Please try there

**Comment by runxel** [comment]
Nope, doesn't work.
Gives me now `preprocessor command failed` errors for zips tho.

Also the whole output is now cluttered with 
```log
<somepath>/.DS_Store adapter: postprocprefix
```
Huh??? Other file types as well. With Alpha 5 it seems rga just looks into _everything_.

**Comment by phiresky** [comment]
I can't reproduce this. If I run `rga --rga-adapters=-zip,sqlite fell` in the `exampledir` in the repo, the result is as expected. Please send a minimal reproducible example.

**Comment by runxel** [comment]
> Please send a minimal reproducible example.

How can I do that?
Also, is this config saved somewhere so I can look into that?

**Comment by lafrenierejm** [comment]
> > Please send a minimal reproducible example.
> 
> How can I do that?

@runxel In this case, a minimum working example would mostly consist of you sharing a file that results in the buggy behavior when running `rga` against it. If your original file is large or contains sensitive information, you might need to construct a new file for testing. If you're willing to do a little extra work, you could even raise a PR adding that new file to `exampledir/` with corresponding tests that fail.

> Also, is this config saved somewhere so I can look into that?

Yes. `rga` uses [directories-next](https://crates.io/crates/directories-next), so the location of the config file varies by OS:
- macOS: `~/Library/Application Support/ripgrep-all/config.jsonc`
- Linux: `$XDG_CONFIG_HOME/ripgrep-all/config.jsonc` or `~/.confic/ripgrep-all/config.json` if `$XDG_CONFIG_HOME` isn't set
- Windows: `%AppData%/ripgrep-all/config.json`

**Comment by phiresky** [comment]
Both `--rga-adapters=-zip` and `"adapters": ["-zip"]` in the config file work (for me).

**Comment by runxel** [comment]
Coming back to this because this does not work at all in 0.10.6. @phiresky 
For other stumbling upon this: Putting in `"adapters": "-zip,sqlite",` does not work; RGA will nag that it is not an array. Okay, easy fix, `"adapters": ["-zip,sqlite"]` does the trick. Or so I thought.
But now I get this error when running rga: `Error: Could not remove adapter zip,sqlite: Not in list`.
Looks like I can't win. :D

**Comment by phiresky** [comment]
the syntax is probably `["-zip", "sqlite"]` though i didn't check

**Comment by phiresky** [comment]
creating a list that can be both additive as well as overriding is challenging, and then getting intuitive support for the same syntax in a config file as well as cli args while keeping it comfortable is even more challenging ;) esp when the config format is added later than the cli syntax

**Comment by lafrenierejm** [comment]
> creating a list that can be both additive as well as overriding is challenging, and then getting intuitive support for the same syntax in a config file as well as cli args while keeping it comfortable is even more challenging ;) esp when the config format is added later than the cli syntax

Since ripgrep-all isn't yet at 1.0.0, what would you think about making a breaking change to the config file schema to have two distinct lists? I'm thinking they could be something like:

- `adapters_enable`: List of adapters to enable in addition to any default adapters.
- `adapters_disable`: List of adapters to disable. This can be used to disable default adapters. Entries in this list take priority over entries in `adapters_enable`.
