### ISSUE TITLE
Respect .rgignore

### ISSUE THREAD

**Issue by rsuhada** [phiresky/ripgrep-all#20]
Hi, first of all thanks for this - this is incredibly useful for me.
Caching makes all the difference comparing to the slow pdfgrep!

It seems rga doesn't respect .rgignore file? Would it be possible to add it please?

**Comment by phiresky** [comment]
you mean a `.ignore` file? afaik rgignore does not [exist (anymore?)](https://github.com/BurntSushi/ripgrep/issues/673)

It should respect those same as .gitignore etc (by default). it not i can check

**Comment by phiresky** [comment]
and thanks :)

**Comment by rsuhada** [comment]
OK, I've updated everything and both these work:

    rg "bla" --ignore-file ~/.ignore
    rga "bla" --ignore-file ~/.ignore 

The global ~/.config/git/ignore doesn't seem to work (?). In any case this is fine for me - I want to keep some files under git, but not search them and vice versa. Having a separate git and rg/ag ignore is better.

Thanks again!

**Comment by BurntSushi** [comment]
.gitignore, .ignore and .rgignore are all supported in ripgrep. Global git ignores should also work.

**Comment by phiresky** [comment]
> The global ~/.config/git/ignore doesn't seem to work (?).

I don't think that file exists by default? You probably set `git config --global core.excludesfile` to that filename. I don't think rg supports parsing git configs to find ignore files. But you could probably make a [rg config file](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file) and add `ignore-file=.../.config/git/ignore` there.

**Comment by BurntSushi** [comment]
> I don't think rg supports parsing git configs to find ignore files.

@phiresky It does: https://docs.rs/ignore/0.4.7/ignore/gitignore/struct.Gitignore.html#method.global

Although it is not perfect, e.g., https://github.com/BurntSushi/ripgrep/issues/1014
