### ISSUE TITLE
Support Maildir as well as mbox

### ISSUE THREAD

**Issue by freswa** [phiresky/ripgrep-all#202]
**Is your feature request related to a problem? Please describe.**
#104 merged a mbox adapter. It parses mbox files and passes attachments to other adapters. Thunderbird has experimental support for Maildirs, other tools such as mutt, neomutt and mu work on maildirs. Those aren't supported yet.

**Describe the solution you'd like**
Support for Maildirs.

**Describe alternatives you've considered**
Using Mu, but that's not as powerful as ripgrep-all :)

**Comment by vejkse** [comment]
I'm using rga successfully in a Thunderbird maildir.  These are just directories with .eml files.  You need to explicitly allow the `mail` adapter: `rga --rga-adapters=+mail`.

**Comment by freswa** [comment]
I'm talking about UNIX maidirs. The files have no extension and are mime-type `message/rfc822`

**Comment by lafrenierejm** [comment]
> I'm talking about UNIX maidirs. The files have no extension and are mime-type `message/rfc822`

@freswa That mime-type is already included in the `mail` adapter (see source code [here](https://github.com/phiresky/ripgrep-all/blob/dcbcb7147f70baef10177177b50ac482f868ace8/src/adapters/mbox.rs#L13)). You should be able to search them as long as you have by enabling the mail adapter as [vejkse recommended](https://github.com/phiresky/ripgrep-all/issues/202#issuecomment-2383254242) and pass `--rga-accurate` to enable matching by mime-type:

```shell
rga --rga-accurate --rga-adapters=+mail
```

**Comment by freswa** [comment]
Sorry, should have rtfm more carefully. Thanks!
