### ISSUE TITLE
feature request: native support for xpi file extension (its just a standard .zip file) for Firefox extensions

### ISSUE THREAD

**Issue by sweetbbak** [phiresky/ripgrep-all#212]
**Is your feature request related to a problem? Please describe.**
Today I found myself trying to ripgrep-all through some backups looking for some terms that I knew existed in some extensions, but I couldn't find them. I realized that rga doesn't recognize .xpi files. (the default format for firefox extensions)

**Describe the solution you'd like**
.xpi files are just renamed .zip files so maybe it could be fairly trivial to implement the ability to just treat them as .zip files

**Describe alternatives you've considered**
Its also understandable if not since all you need to do is rename a .xpi file extension (firefox browser extension filetype) to .zip and you can treat it as a zip file from that point onward.

**Comment by sweetbbak** [comment]
I probably shouldn't have made this issue, I went and made a PR instead.

**Comment by phiresky** [comment]
thanks
