### ISSUE TITLE
Is it safe to interrupt a started search?

### ISSUE THREAD

**Issue by xfilesee34** [phiresky/ripgrep-all#227]
Is there a possibility that ripgrep-all corrupts any file it is searching? Is it safe to use ctrl + c to interrupt search?

**Comment by lafrenierejm** [comment]
No, ripgrep-all shouldn't be able to corrupt any files it searches. It does not modify any of the files it is searching. Simply reading a file should not be capable of corrupting it unless you are dealing with failing hardware or a buggy filesystem.

**Comment by phiresky** [comment]
yes, it's safe
