### ISSUE TITLE
mail adapter not working

### ISSUE THREAD

**Issue by sinepgnol** [phiresky/ripgrep-all#249]
**Describe the bug**
Mail adapter doesn't work even after enabling it with "--rga-adapters=+mail"

**To Reproduce**
rga --rga-adapters=+mail 

Attach example file:

Run command:

**Output**

**Screenshots**

**Operating System and Version**
macOS 14.6.1.

**Output of `rga --version`**
ripgrep-all 0.10.6

**Comment by phiresky** [comment]
missing info

**Comment by sinepgnol** [comment]
what info is missing?

**Comment by lafrenierejm** [comment]
> what info is missing?

@sinepgnol At the very least this bug report is missing an example file/directory and the output you currently receive.
