### ISSUE TITLE
AppImage or Flathub

### ISSUE THREAD

**Issue by richardstevenhack** [phiresky/ripgrep-all#267]
**Is your feature request related to a problem? Please describe.**

If you're going to do "Linux", DO LINUX! Do not do "binaries". Do not do "pip" in Python (many distros are locked down.)

**Describe the solution you'd like**

You need an AppImage and/or a Flatpak (preferably both.)

**Describe alternatives you've considered**

None. Not using the product is my only option on openSUSE Tumbleweed.

**Additional context**

None.

**Comment by phiresky** [comment]
Open to PRs
