### ISSUE TITLE
Email: search precise fields

### ISSUE THREAD

**Issue by tobiasBora** [phiresky/ripgrep-all#268]
**Is your feature request related to a problem? Please describe.**

I can't find a good tool to search my thunderbird emails (thunderbird is fairly bad, e.g. I cannot search through all my mail boxes at once a mail between two dates). It seems like ripgrep-all can parse emails, but it is not possible for now to filter on some fields of the email, like "the title should contain XXX", or "the date should be before date1 and after date2"…

**Describe the solution you'd like**

It would be great to allow searches like:
```
$ rga -i --email-title "my title" --email-sender "alice" --email-date-between 2022-12-06 2024-12-06 --content "hello"
```
an even more wonderful option would be to allow more complex boolean expressions, involving `--and`, `--or`, `--not`. I can imagine two syntaxes: either one involving parenthesis like:
```
$ rga -i ( --email-sender "alice" --or --email-sender "bob" ) --and ( --email-date-before 2022-12-06 --or --email-date-after 2024-12-06 )
```
I can also imagine a different (possibly easier to parse but harder to use) syntax involving the polish notation (i.e. write the operator in front like `or a b` instead of `a or b`) that requires no parenthesis. For instance, in polish notation the above would translate into:
```
$ rga -i --and --or --email-sender "alice" --email-sender "bob" --or --email-date-before 2022-12-06 --email-date-after 2024-12-06
```

**Describe alternatives you've considered**

Found no good solution so far.

**Comment by phiresky** [comment]
this is a nice idea, but out of scope. rga is a line-based text search tool that converts non-plaintext files to plaintext before searching them with a normal linear search. searching mbox files is already at the boundary of the scope because rga does not do real indexing and for files 1GB+ in size you kind of want proper indexing.

**Comment by tobiasBora** [comment]
Too bad, but I understand.
