### ISSUE TITLE
Failed to run the demo.

### ISSUE THREAD

**Issue by hongyi-zhao** [phiresky/ripgrep-all#27]
Hi,

See the following:

$ rga "hello" ./demo/ 
./demo/hello.sqlite3
tbl: greeting='hello', from='sqlite database!'

./demo/greeting.mkv
metadata: chapters.chapter.0.tags.title="Chapter 1: Hello"
00:08.398 --> 00:11.758: Hello from a movie!
./demo/hello.odt: preprocessor command failed: '"rga-preproc" "./demo/hello.odt"': 
-------------------------------------------------------------------------------
adapter: pandoc
pandoc: Cannot read archive from stdin
CallStack (from HasCallStack):
  error, called at pandoc.hs:1300:22 in main:Main
Error: subprocess failed: ExitStatus(ExitStatus(256))
-------------------------------------------------------------------------------
./demo/somearchive.zip: preprocessor command failed: '"rga-preproc" "./demo/somearchive.zip"': 
-------------------------------------------------------------------------------
adapter: zip
adapter: pandoc
pandoc: Cannot read archive from stdin
CallStack (from HasCallStack):
  error, called at pandoc.hs:1300:22 in main:Main
Error: subprocess failed: ExitStatus(ExitStatus(256))
-------------------------------------------------------------------------------

Any hints?

ps.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

$ rga -V
ripgrep-all 0.9.2

**Comment by phiresky** [comment]
You have an outdated pandoc version
