### ISSUE TITLE
Problem with `--pre` parameter when calling ripgrep

### ISSUE THREAD

**Issue by Kudlaty01** [phiresky/ripgrep-all#33]
On Debian 10, when attempting to use `rga` (0.9.3) with any search, it results with `ripgrep` (11.0.2) error screen stating that:
```
error: Found argument '--pre' which wasn't expected, or isn't valid in this context
	Did you mean --pretty?
```
After taking the latest rg binary from the repo I still get this issue.
Is there any workaround or am I missing anything?

**Comment by phiresky** [comment]
Can you run `rga --rg-version` to check which version of ripgrep rga is actually calling? Because this really looks like an error that can only happen if rg is old.

Also, try running `rg test --pre=cat` in some directory to see if your rg accepts the pre argument.

**Comment by Kudlaty01** [comment]
Sorry for the late resaponse,
Both commands return the same error screen as presented. When I try `rg --version` it says
```
ripgrep 0.7.1
-AVX +SIMD
```

**Comment by phiresky** [comment]
Jep, that's a really outdated version (like 3 years). Nothing I can do here
really, sorry.

**Comment by Kudlaty01** [comment]
That's totally right!
I must have put a pre-compiled binary in my bin folder a long time ago and now that it's in the system repositories I see I can just install it the right way.
Thank you for pointing me out that outdated version!
