### ISSUE TITLE
Add support for xlsx and ods

### ISSUE THREAD

**Issue by brmmm3** [phiresky/ripgrep-all#36]
Would be great to see support for above file formats using crate calamine.

**Comment by phiresky** [comment]
they are supported (via pandoc)

**Comment by phiresky** [comment]
nvm

**Comment by brmmm3** [comment]
Companies are using Excel extensively. So adding support for this format would be a great improvement ;-)

**Comment by phiresky** [comment]
Do you have a proposal for what the plain text output could look like?

**Comment by brmmm3** [comment]
Sheet: <Name>
    <RowNr:ColNr>: Text

**Comment by phiresky** [comment]
Shouldn't be too hard. Main problem is that calamine needs seek: [calamine::Reader](https://docs.rs/calamine/0.16.1/calamine/trait.Reader.html). We can't seek usually because we are not always reading from the file system (could be in archives etc). So either we would have to read the whole file to RAM, or extract them to a temporary directory.

Might need to investigate how much seeking calamine actually does and why.

**Comment by petRUShka** [comment]
Add +1 for this feature

**Comment by lkyhfx** [comment]
Add +1 for this feature, really needed.

**Comment by lkyhfx** [comment]
After look into the code and do some experiments, I found that there is a possible and simple solution that don't need to write a custom adapter for excel (and other microsoft office file type such as powerpoint). Excel file simply is a zip archive of bunch of xml files, we can treat excel files as zip files, then using zip's adapter and pipeline. I have tried to simply rename the extension to .zip then use rga to search the content inside original excel file, the search result  is acceptable. The xml tag even have the column and row of the search term. 
I know nothing about Rust, and really want support for excel file. Perhaps someone can tell me where to start to do this little change, and I will try to do it myself if the author don't have time.

**Comment by phiresky** [comment]
Starting with 1.0.0, it's possible to add custom adapters [via the config file](https://github.com/phiresky/ripgrep-all/wiki). If someone has a good suggestion for this file type please post it in [show-your-adapter](https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter)
