### ISSUE TITLE
possible bug with search path

### ISSUE THREAD

**Issue by nDanielGH** [phiresky/ripgrep-all#37]
Hi.
In the following example I'm looking for "static analysis", and I expect to find this phrase in 2 PDFs, in a folder called Compi:
`rga "static analysis" . --no-heading -m=1`
rga outputs nothing.
However,
`mv Compi compi`
`rga "static analysis" . --no-heading -m=1`
will output:
`./compi/Lectures/12-abstract-interp-fullscreen.pdf:Page 217: ★   30% Static Analysis`
`./compi/Lectures/08-analysis-fullscreen.pdf:Page 8:             Static Analysis`
Am I missing something?
Thanks.

**Comment by phiresky** [comment]
Interesting. This should not be happening, though I'm not sure why it is.

My first thought is a bug in caching - can you try `rga --rga-no-cache "static anaylsis" .` and see if that works? Also, try `rga-preproc ./Compi/Lectures/12-abstract-interp-fullscreen.pdf` and see if the output contains the text or not. If possible you can also send me the relevant file(s) so I can check myself.

Also, what OS are you on? If you are on a case-insensitive FS that might also cause weird issues.

**Comment by nDanielGH** [comment]
First thing I tried was disabling caching, forgot to mention that.
rga-preproc does show the searched text.
OS is arch linux, FS is btrfs.
I am attaching the folder as it is on my drive.
Curiously, running the search on my home directory not only finds it in "compi", it also finds it in the zip I'm attaching, but keeps missing it in "Compi".
[Compi.zip](https://github.com/phiresky/ripgrep-all/files/4281687/Compi.zip)

**Comment by phiresky** [comment]
Thanks.

I tried extracting your zip on tmpfs, ext4, and btrfs, but it works everywhere like expected, so I can't reproduce your issue sadly..

Some things you can try that might narrow it down:

1. extract your own zip in a different folder of the same drive as well as a different drive, see if it still happens then
2. maybe some permissions issue with the dirs?
3. rga turns on smart-case for ripgrep by default - maybe you have a ripgreprc or something that influences this? Try searching for "Static Analysis", "static" and "Static" to see if that's different. If you have a ripgreprc, what are the contents?
4. does it still happen if you rename the folder back to it's previous name? does it happen if you name it something different, both with mixed casing as well as just lowercase?
5. Try `-j 1` to disable threading
6. Maybe you have a .gitignore/.ignore file (e.g. in your home directory root) that affects search?
7. Try `rga --files` to see a list of what files rg is searching (so if some ignore file is affecting it)
8. Try deleting `~/.cache/rga`, maybe the no-cache flag is not working for some reason
9. Try `rg -uu -a -l . .` and `rg -a -l . .` to see if rg itself is looking at the files or not

**Comment by nDanielGH** [comment]
:facepalm:
It was my gitignore.
Thanks!
