### ISSUE TITLE
rga-accurate problem for pdf files without filename extension

### ISSUE THREAD

**Issue by theHausdorffMetric** [phiresky/ripgrep-all#39]
I can't get rga --rga-accurate to work on pdfs with no filename extension.
1) I take some random pdfs and copy them to random filenames without filename extensions
2) I check that "file *" correctly identifies both original and copies as pdf files
3) I search for a generic word which occurs in all/most pdfs: rga --rga-accurate -l "the"
This only lists the pdfs with the filename extension ".pdf" but not the renamed copies without ".pdf" file extension.

**Comment by phiresky** [comment]
this was just because the mime type for pdfs was missing. fixed in 0.9.5 :)

**Comment by phiresky** [comment]
thanks for reporting it! i don't think that situation happens very often (pdf files usually have their extension as opposed to e.g. zip or sqlite files), but still good to have

**Comment by theHausdorffMetric** [comment]
Well thanks for a wonderful tool and ++thanks for such a wonderfully quick fix!
My intended use is for Joplin (a quite good foss note keeping tool) which unfortunately does not search in note attachments, and saves attached files with a hash as file name (thus killing the filename extension). Now, I'll rga through attached files :-)
