### ISSUE TITLE
No such file or directory (os error 2)

### ISSUE THREAD

**Issue by mmastrac** [phiresky/ripgrep-all#4]
Unsure what's going on here. Running on my unraid server, `rg` binary installed in current directory.

```
# PATH=$PATH:. rga "..." /mnt/user/backup/
/mnt/user/backup/_omitted_.zip: No such file or directory (os error 2)
```

File exists:

```
root@Tower:/tmp/rga# ls -l /mnt/user/backup/_omitted_.zip
-rw-rw-rw- 1 nobody users ... Aug  4  2018 /mnt/user/backup/_omitted_.zip
```

ripgrep exists:

```
# PATH=$PATH:. rg
error: The following required arguments were not provided:
    <PATTERN>
```

**Comment by phiresky** [comment]
Did you try exporting the PATH variable?
export PATH=$PATH:.
rga ......

I've seen that error happen when ripgrep tries to call rga-preproc but can't find the binary.

**Comment by phiresky** [comment]
Detail: `rga hi` calls `rg --pre=rga-preproc hi [...other options]`, which in turn calls `rga-preproc`. So it searches PATH for rga-preproc. If you set PATH inline as above, only the shell sees the modified path, but not `rga-preproc`.

**Comment by mmastrac** [comment]
That worked. I'll open a new issue for a better error if it can't find `rga-preproc`.

**Comment by segeljakt** [comment]
I'm getting this error when running the `rga-fzf` command defined in the README. Should I open another issue or can this be re-opened?

**Comment by phiresky** [comment]
@segeljakt that should only happen when no results are found. I've fixed that instance here: https://github.com/phiresky/ripgrep-all/commit/38185dda21eae77ccd9b8bd6a683ae4d657627e8 . If you're still getting it, open a new issue
