### ISSUE TITLE
cache-max-blob-len no effect with certain files

### ISSUE THREAD

**Issue by varagnac** [phiresky/ripgrep-all#40]
I run `rga whatever .` in the home directory routinely to cache all the files, to achieve a 0-delay integration with fzf. I currently have a cache with a size of 228M in ~/.cache/rga/data.mdb , which is pretty small, and I don't care about the size of the caches.
However, some files are not cached no matter how big I set the value with  --cache-max-blob-len. For instance I've tried to run it with `rga -L whatever . --rga-cache-max-blob-len 100000000000`, there'll still be files not cached (for rga will spend plenty of times when searching around them, I can see `pdftotext` process running with rga pointing to these files) after running the command. 
The files are typically large pdf files. The largest one is around 8M or 12.4M after conversion to text file without any compression.
Am I doing anything wrong?

**Comment by phiresky** [comment]
Mh, no that should work. Only thing I can think of is that errors are not cached as far as I remember. So if e.g. pdftotext takes a while and then errors out, the result will not be cached no matter how long the file. Could you see what `RUST_LOG=trace rga-preproc the-pdf-filename.pdf` outputs? Or even better, send me a sample file.

**Comment by varagnac** [comment]
Ok I found the problem. Instead of `--rga-cache-max-blob-len <cache-max-blob-len>` as stated in the help message I should have used `--rga-cache-max-blob-len=<cache-max-blob-len>`.

**Comment by phiresky** [comment]
uhh ok that makes sense. it should have shown `100000000000: No such file or directory (os error 2)` then in the first command you tried though, didn't it?

**Comment by varagnac** [comment]
No it showed no message, it just kept running..
