### ISSUE TITLE
Adapter documentation... request for wireshark adapter

### ISSUE THREAD

**Issue by ldwSpirent** [phiresky/ripgrep-all#42]
Do you have documentation for creating ripgrep-all adapters?

I would like to have a ripgrep adapter for wireshark files (.pcap, .pcapng, etc).  A general purpose adapter would have to be highly configurable, but in my case, I generally convert to text using this command:
`tshark -V -Y "(ngap || nas-5gs || s1ap || sip || diameter)" -r ${wireshark_file_name}`

A general purpose adapter could just use `tshark -V -r ${wireshark_file_name}`.

An even more general purpose adapter could allow you to specify the following parameters:
  `RGA_USER_ADAPTER=${path_to_executable}`
  `RGA_USER_ADAPTER_FLAGS=${flags}`

As in ... 
   `RGA_USER_ADAPTER=/usr/bin/tshark`
   `RGA_USER_ADAPTER_FLAGS="-V -r {}"`
or ...
   `RGA_USER_ADAPTER_FLAGS="-V -Y \"(ngap || nas-5gs || s1ap || sip || diameter)\" -r {}"`

Note also that there do exist some rust pcap libraries...
- [pcap crate](https://docs.rs/pcap/0.7.0/pcap/)
- [rusticata/pcap-parser](https://github.com/rusticata/pcap-parser)
- [ebfull/pcap](https://github.com/ebfull/pcap)
- [courvoif/pcap-file](https://github.com/courvoif/pcap-file)

**Comment by phiresky** [comment]
For simple adapters that use an external tool, creating it is pretty easy, see the pdf extractor for example:
https://github.com/phiresky/ripgrep-all/blob/master/src/adapters/poppler.rs

It would be possible to allow external plugins etc via a config file and just let it run arbitrary external commands, but so far my approach has been to "keep it close" so I can ensure the quality / performance stays high, especially for file types where there exist rust libraries.

**Comment by phiresky** [comment]
Starting with 1.0.0, it's possible to add custom adapters [via the config file](https://github.com/phiresky/ripgrep-all/wiki). If someone has a good suggestion for this file type please post it in [show-your-adapter](https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter)
