### ISSUE TITLE
feature_request(windows): third-party instead of built-in dependencies

### ISSUE THREAD

**Issue by Kristinita** [phiresky/ripgrep-all#45]
### 1. Summary

It would be nice, if would be possible to use third-party dependencies instead of built-in dependencies, that implemented to ripgrep-all archive.

It would be nice to have normal dependencies management instead of old-school built-in dependencies.

#### 2.1. Dependencies installation

Users [**install ripgrep-all via Chocolatey**](https://chocolatey.org/packages/ripgrep-all) — [**Windows package manager**](https://chocolatey.org/). We can add dependencies to [**ripgrep-all Chocolatey package**](https://github.com/jonasw234/au-packages/tree/master/ripgrep-all). For example, we add this line [**to this file**](https://github.com/jonasw234/au-packages/blob/f6f9e846d031f520f4a1b38f44bd0caa9d92b4de/ripgrep-all/ripgrep-all.nuspec#L30-L32):

```xml
<dependency id="pandoc" />
```

→ Chocolatey install [**pandoc**](https://chocolatey.org/packages/pandoc), when Windows install ripgrep-all via Chocolatey.

Chocolatey works with dependencies as [**pip with `requirements.txt`**](https://pip.pypa.io/en/stable/user_guide/#requirements-files) or [**npm with `package.json`**](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file).

#### 2.2. lib

Now `pandoc.exe` to ripgrep-all archive not necessary. ripgrep-all developers can remove this file from `ripgrep_all-{version}.7z` file. ripgrep-all will use `pandoc.exe` version from [**`PATH` environment variable**](https://superuser.com/a/284351/572069).

#### 3.1. Updates

Users will be able to have newest or specific dependencies versions and will not wait until the ripgrep-all developers will adds new version of dependency. Users can always use required dependencies versions.

#### 3.2. Disk space

Built-in ripgrep-all dependencies take up space on users hard drives. Users, that already have the newest versions of Pandoc and Poppler, don't need extra old versions of these softwares.

### 4. Additional links

1. [**How Chocolatey saves my time**](https://craigporteous.com/how-chocolatey-saves-me-time/)
1. [**Creating Chocolatey Packages**](https://chocolatey.org/docs/create-packages)

Thanks.

**Comment by phiresky** [comment]
In general I agree - the reason I bundle dependencies for Windows is that it doesn't have any dependency management built in. I really don't want to maintain multiple packaging solutions for windows, so I'm not sure if all windows users would be satisfied with being forced to use Chocolatey?

**Comment by phiresky** [comment]
Contacted the maintainer of the chocolatey package to ask them for advice

**Comment by phiresky** [comment]
fixed in 0.9.6 https://github.com/phiresky/ripgrep-all/releases

Waiting for chocolatey package to be updated (https://github.com/jonasw234/au-packages/issues/1)
