### ISSUE TITLE
preprocessor command could not start: path to my preprocess.sh

### ISSUE THREAD

**Issue by Gahamelas** [phiresky/ripgrep-all#49]
I am getting this error.
I am using the arguments: `("--pre" "~/pdf-tools/preprocess.sh")))`

Inside preprocess.sh is:

```
$ cat preprocess
#!/bin/sh

exec pdftotext - -
```

Any help is welcome, thanks.

**Comment by phiresky** [comment]
ripgrep-all does not support the --pre argument
