### ISSUE TITLE
DOCX but not DOC

### ISSUE THREAD

**Issue by Gahamelas** [phiresky/ripgrep-all#55]
Do I understand correctly that DOC is not searched but DOCX is? I made a test where I confirmed this.

**Comment by Kristinita** [comment]
**Type: Reply** :speech_balloon: 

Yes, ripgrep-all 0.9.6 not support this format. We waits [**`DjVu`, `Doc`, `RTF` and `CHM` supporting**](https://github.com/phiresky/ripgrep-all/issues/14#issuecomment-629829472).

Thanks.

**Comment by Gahamelas** [comment]
thanks
