### ISSUE TITLE
Better error if rga-preproc can't be found

### ISSUE THREAD

**Issue by mmastrac** [phiresky/ripgrep-all#6]
Right now we get `No such file or directory (os error 2)` with no indication of what's missing.

**Comment by phiresky** [comment]
Yep. Sadly that error is thrown by ripgrep itself, so I can't directly influence it. I've opened an issue there: https://github.com/BurntSushi/ripgrep/issues/1302. We can leave this open until it is fixed there.

**Comment by phiresky** [comment]
Looks like it's fixed in the next version of ripgrep! :)

**Comment by mmastrac** [comment]
Thanks for forwarding the bug report!
