### ISSUE TITLE
Add adapter chaining

### ISSUE THREAD

**Issue by phiresky** [phiresky/ripgrep-all#64]
Add adapters that are not invoked normally (they have no Matchers), but can be added as post(and pre?) processors to other adapters.

possible functionality:

1. ascii-page break to page number prefixes function. Currently a function hard coded in the poppler adapter. required to finish conversion of pdftotext as a declaratively defined custom internal adapter 
2. strip binary / gremlin characters (#46)
3. encoding transformation (#26, #47)
4. ???
5. maybe even make caching one of these? preprocess = loadcache&&bailout, postprocess=savecache. probably not all that useful though.

**Comment by egrieco** [comment]
This would make ripgrep-all even more useful e.g. being able to have pandoc convert html to either Markdown or plain text would eliminate spurious matches in tags.

**Comment by phiresky** [comment]
in 0.10 adapters can be chained
