### ISSUE TITLE
.pptx file not showing content

### ISSUE THREAD

**Issue by JackKuo-tw** [phiresky/ripgrep-all#69]
This is what I encounter:

![圖片](https://user-images.githubusercontent.com/21074047/90085929-b3613780-dd4b-11ea-9416-4ed7f9a5d9e5.png)

- Server: Ubuntu 18.04 LTS
- LANG=en_US.UTF-8

**Comment by JackKuo-tw** [comment]
Sure, [here you are](https://www.dropbox.com/s/y8pqt1fdn6enu41/20200709.pptx?dl=0)

**Comment by lafrenierejm** [comment]
@Konfekt shared https://github.com/phiresky/ripgrep-all/discussions/199, which uses https://github.com/ssine/pptx2md via a custom adapter to support Powerpoint files.
