### ISSUE TITLE
Open up the Wiki page

### ISSUE THREAD

**Issue by m040601** [phiresky/ripgrep-all#74]
Is there any reason you have the wiki page locked or don't wish to have it open ?

I ask because this is such a very generic usefull tool, that plugs with so many different other tools, caters to many different types of "uses" and "users".

I dont' mean this as an additional place for the "official" docs or for "selling" ripgrep-all. You already have that pretty well covered in the docs, homepage etc.

Neither do I mean it as a place for developers/programmers comparing/discussing the performance/ins/outs/pros/cons of ripgrep. You already have that in full control in the repo and the issues.

I mean the wiki as place for the **end users**. The ones that read pdfs and listen to mp3's. Only. Not the ones that are going to use "git", or github issues. There is a big difference betwenn forking the repo, to submit a pull request to the docs, and a quick wiki edit. Some end users might do it, but the majority is not gonna fork a repo just for adding a small tip.

This means it will be impossible for you to maintain or document every single use case, trick or hack this tool can be used for.

Even more, it will be impossible to even "imagine" the cool things many different minds can come up using this tool. The kind of things that make you think: "this little oneliner isnt that complicated, why hadnt I thought myself about that first"

Why not have a free space, the wiki, to let users, themselves, post their snippets, use cases, pipes, gotchas, etc. You can at least give it a shot, and later if you feel like close it again.

Have a look at the wiki of projects like fzf (or lf, or ranger) for example. So much value can be extracted from that community wiki.

**Comment by phiresky** [comment]
> Is there any reason you have the wiki page locked or don't wish to have it open ?

There's not really a specific reason why I haven't added a wiki, just that I don't really have any content to put there. Tbh I didn't even know that contributing changes to Wikis on GH was different than contributing changes to the repo itself. 

Once custom adapters work I'll probably add a list of ideas from me and other people about which file adapters can be added, and I guess that would something that could be done in Wiki instead of the main repo.

**Comment by lafrenierejm** [comment]
[The wiki](https://github.com/phiresky/ripgrep-all/wiki) has been opened since this issue was first logged. @phiresky IMO this can be safely closed.
