### ISSUE TITLE
Current master branch broken during refactoring, doesn't compile - missing paths for crates and incorrect version

### ISSUE THREAD

**Issue by AlexMikhalev** [phiresky/ripgrep-all#75]
Current master branch broken during refactoring, doesn't compile - missing paths for crates and incorrect versions:
```
cargo build 
error: failed to get `zip` as a dependency of package `ripgrep_all v0.9.7-alpha.0 (/home/alex/ripgrep-all)`

Caused by:
  failed to load source for dependency `zip`

Caused by:
  Unable to update /home/alex/rust_code/zip-rs

Caused by:
  failed to read `/home/alex/rust_code/zip-rs/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

```

**Comment by rickhg12hs** [comment]
Same as #67?

**Comment by rickhg12hs** [comment]
Possibly related: https://github.com/phiresky/ripgrep-all/commit/bcc01f7a62fea3f5cc49247fc8cc510fe30441ff#r42231033

**Comment by AlexMikhalev** [comment]
Yes, this seems to be breaking change.

**Comment by phiresky** [comment]
Yes, current master is broken in many places since I'm refactoring it to
solve custom adapters, but I got stuck trying to figure out
lifetimes/ownership. If you need a working source code snapshot, use the
latest tag.

**Comment by rickhg12hs** [comment]
> If you need a working source code snapshot, use the latest tag.

This also seems to be working for me.

```
cargo +nightly install --git https://github.com/phiresky/ripgrep-all.git --rev 977074c6e64bd8cc304e0d68e07243ccab9cb736
```

**Comment by AlexMikhalev** [comment]
Do we have to use nightly?

**Comment by ramifications123** [comment]
> > If you need a working source code snapshot, use the latest tag.
> 
> This also seems to be working for me.
> 
> ```
> cargo +nightly install --git https://github.com/phiresky/ripgrep-all.git --rev 977074c6e64bd8cc304e0d68e07243ccab9cb736
> ```

We'll have to use nightly until a new version comes out.

**Comment by phiresky** [comment]
fixed
