### ISSUE TITLE
pdftotext not found in OSX

### ISSUE THREAD

**Issue by pakoito** [phiresky/ripgrep-all#8]
There are no simple instructions about how to use pdftotext or poppler-utils in OSX, nor are they available on Brew or Cargo that I've found.

**Comment by phiresky** [comment]
Looks like it should be included in [poppler](https://formulae.brew.sh/formula/poppler), can you try that?

**Comment by pakoito** [comment]
That did the trick. Thanks!

**Comment by phiresky** [comment]
Can you say what other packages you installed over Homebrew so I can add it
to the read me?

**Comment by pakoito** [comment]
`brew install tesseract`, which I already had, and nothing else
