### ISSUE TITLE
brew troubles?

### ISSUE THREAD

**Issue by hyperjeff** [phiresky/ripgrep-all#80]
I did an install on macOS Catalina (10.15.7) using `brew install rga` and for all files I test this on I get this error when I try `rga testing`:

`-------------------------------------------------------------------------------`
`./some file.pdf: preprocessor command failed: '"/usr/local/bin/rga-preproc" "./some file.pdf"': `
`-------------------------------------------------------------------------------`
`adapter: poppler`
`Error: Couldn't open file '-'`
`Error: Broken pipe (os error 32)`

So then I went ahead and installed all the additional libraries mentioned in the readme with `brew install pandoc poppler tesseract ffmpeg` but this didn't seem to help at all. Even tried reinstalling rga after that.

**Comment by phiresky** [comment]
This is probably brew installing some weird version of poppler / pdftotext.

Can you send the output of `pdftotext -v`

Should show something like

```
pdftotext version 0.84.0
Copyright 2005-2019 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```

**Comment by sballin** [comment]
Happening to me too on Big Sur. I have rga 0.9.6, pdftotext 3.03, poppler 20.11.0, pandoc 2.11.2, and tesseract 4.1.1

**Comment by hyperjeff** [comment]
rga 0.9.6, pdftotext 3.02, tesseract 4.1.1, poppler 20.11.0,  pandoc 2.11.2

**Comment by dmrd** [comment]
Hitting a similar issue on Big Sur on m1 MacBook.  `pdftotext file.pdf` works fine, but calling rga-preproc fails with error mentioned above:
```
/usr/local/bin/rga-preproc workbook.pdf
adapter: poppler
I/O Error: Couldn't open file '-'
Error: Broken pipe (os error 32)
```


```
pdftotext -v
pdftotext version 3.03
Copyright 1996-2011 Glyph & Cog, LLC
```

**Comment by azu** [comment]
In my case, `rga query` work fine.
But, `rga --files-with-matches query` show following error.

```
*.pdf:
-------------------------------------------------------------------------------
adapter: poppler
Error: Broken pipe (os error 32)
-------------------------------------------------------------------------------
*.epub:
-------------------------------------------------------------------------------
adapter: pandoc
Error: Broken pipe (os error 32)
```

env

```
$ pdftotext -v
pdftotext version 22.02.0
Copyright 2005-2022 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
$ pandoc -v
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.2,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /Users/azu/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

```

**Comment by hyperjeff** [comment]
Sorry, I'd forgotton all about this. I just re-installed rga via brew and it works a-ok. Going to close my issue on this.
