### ISSUE TITLE
Investigate integration with skim

### ISSUE THREAD

**Issue by phiresky** [phiresky/ripgrep-all#81]
https://github.com/lotabout/skim

Currently, there is a shell based integration with fzf in the readme, as well as a better rust-based integration in rga-fzf.rs. But integrating with skim might have advantages:

* using a rust api instead of a shell args api
* allowing opening of configured programs from rga-fzf (and passing parameters such as --search="foo" to evince to open the pdf and highlight the resulting search strings
* no dependency on an external tool

this is low priority though

**Comment by bionicles** [comment]
hey i would very much enjoy this because I like rust and want to make a rust CLI + terminal UI, the more we can put in Rust the better for integrations

**Comment by egrieco** [comment]
@phiresky from your list above, I take it you would like to see direct integration of `skim` fuzzy search into `ripgrep-all`?

I've integrated skim into an existing project of mine. What exactly do you have in mind for use cases?

**Comment by egrieco** [comment]
Is one of the desired use cases along the lines of [igrep](https://lib.rs/crates/igrep)?

> Runs [grep](https://lib.rs/crates/grep) ([ripgrep's](https://github.com/BurntSushi/ripgrep/) library) in the background, allows interactively pick its results and open selected match in text editor of choice (vim by default).

**Comment by phiresky** [comment]
rga-fzf is integrated with 0.10 and works well
