### ISSUE TITLE
Use zip file seeking when available

### ISSUE THREAD

**Issue by phiresky** [phiresky/ripgrep-all#82]
When zip files are read directly from the file system, we can seek - so we should, this allows archives affected by https://github.com/zip-rs/zip/issues/108 to work as long as they are not within another archive

**Comment by phiresky** [comment]
This should fix https://github.com/phiresky/ripgrep-all/issues/86 for all cases except when an archive is in an archive.

**Comment by blackberryoctopus** [comment]
@phiresky the "Error: Unsupported Zip archive" occurs for my usage on a regular basis. What is the status of addressing this issue? Any plans to deploy a fix?

**Comment by phiresky** [comment]
this will be fixed in the next release

**Comment by blackberryoctopus** [comment]
Thank you so much @phiresky !

**Comment by blackberryoctopus** [comment]
hi @phiresky 
I read through your post outlining how rga is a side project & your time is limited. So, I'm acknowledging you may not be able to answer concretely. 
Do you have any rough idea of when the next release of rga might go out to users?

**Comment by phiresky** [comment]
0.10 is released
