### ISSUE TITLE
sqlite adapter tries to read Thumbs.db (windows thumbnail cache)

### ISSUE THREAD

**Issue by CouleeApps** [phiresky/ripgrep-all#84]
`rga-preproc` throws an error for every Thumbs.db file it searches, as it assumes they are sqlite databases, but they are actually windows thumbnail caches. This only applies to files specifically named `Thumbs.db`.

Specific error thrown:
```
Thumbs.db: preprocessor command failed: '"/usr/local/bin/rga-preproc" "Thumbs.db"':
-------------------------------------------------------------------------------
adapter: sqlite
Error: file is not a database
```

**Comment by phiresky** [comment]
Fixed in 0.10.3
