### ISSUE TITLE
Output incoherent with ripgrep when using a unicode property

### ISSUE THREAD

**Issue by mklcp** [phiresky/ripgrep-all#85]
Hello,
This may be just a minor issue but I can't find an explanation for that:

````

$ echo -abcde | rga -e '-\p{Uppercase}+' 
-abcde
$ echo -abcde | rga -e '-\p{Uppercase}+' | rg -e '-\p{Uppercase}+'
$

````

So when I filter rga's output through the same pattern, but with rg, I get a result different from using rga alone.

When I remove leading `-` everywhere, all is well:

````

$ echo abcde | rga -e '\p{Uppercase}+' | rg -e '\p{Uppercase}+'
$ echo abcde | rga -e '\p{Uppercase}+' 
$

````

So I thought the leading `-` was the source of error, that maybe it lead the argument to be interpreted as an option and not a pattern.. Even if this is true, it still doesn't explain:

````

$ echo abcde- | rg -e '\p{Uppercase}+-' 
$ echo abcde- | rga -e '\p{Uppercase}+-' 
abcde-

````

I'm using arch linux. rg has been installed from the official repos, rga from AUR:

````
$ rga --version
ripgrep-all 0.9.6
$ rg --version
ripgrep 12.1.1
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
$
````

**Comment by phiresky** [comment]
rga always uses "smart-case" matching by adding the --smart-case flag. that is it searches case-insensitive unless an upper case character is present.

This behaviour can be overridden by passing the `--case-sensitive` flag
