### ISSUE TITLE
Unsupported Zip archive

### ISSUE THREAD

**Issue by NuSkooler** [phiresky/ripgrep-all#86]
I'm running into a **lot**  of the "Unsupported Zip archive" errors described in #50 and am hoping to re-open the discussion.

The particular zips are mostly older mid-90's BBS archives. I have thousands of them from various shareware CDs, Bulletin Board Systems, etc. of the era -- so likely produced with the standard DOS PKZIP of the time.

`rga --version`: 0.9.6
`rg --version`: 12.2.1

Windows builds. If I can provide any other information please let me know. This tool looks perfect for munging through these things!

**Comment by alexanderswerdlow** [comment]
I get tons of these errors even from lots of Homebrew archives. I often will search my entire user folder and most of my results will be cluttered by these errors. I think one sensible way to handle it even if the core issue isn't fixed would be to simply count the errors and display the number of errors for say each adapter at the end (and then maybe save them to a log folder somewhere).

**Comment by phiresky** [comment]
Fixed with 0.10
