### ISSUE TITLE
Idea: mailbox & maildir adapter

### ISSUE THREAD

**Issue by vorner** [phiresky/ripgrep-all#89]
Hello

I was thinking, would it make sense to add adapters for parsing emails? They are almost textual, except that:

* The content might be encoded (quoted-printable, base64, …)
* The whole mbox file can also be optionally gzipped
* There can be various attachments (that could be pdf or ebooks...)

**Comment by freswa** [comment]
I love this idea. What about searching through mail attachments (e.g. PDFs) after we parsed the mail?
