### ISSUE TITLE
OSX Homebrew formula

### ISSUE THREAD

**Issue by firedev** [phiresky/ripgrep-all#9]
Hi,

Would be great to have in the Homebrew. I am using `rg` for a while now and `rga` would be useful to have in handy.

**Comment by phiresky** [comment]
Would be awesome to have a package there, but I don't think I can really add it myself since I've never used it and don't have a OSX machine to actually test it...

**Comment by hyperjeff** [comment]
Yes, would be great, especially since "cargo install ripgrep_all" fails on Macs when compiling. (All the requisite libraries seem to compile fine, just not ripgrep_all itself.)

**Comment by phiresky** [comment]
It definitely does compile on MacOS by now, you must be using an outdated Rust version as well (try 1.35.0)

**Comment by hyperjeff** [comment]
Oh, my bad, that was it. Works great! thanks.

**Comment by xgt001** [comment]
@phiresky mind if I try creating a formula for this? :)

**Comment by phiresky** [comment]
sure, go ahead

Am Di., 18. Juni 2019 um 11:34 Uhr schrieb Ganesh Hegde <
notifications@github.com>:

**Comment by filalex77** [comment]
I made a [PR](https://github.com/Homebrew/homebrew-core/pull/42484) with a formula. As soon as #25 is merged and released, I'll update the formula.

**Comment by filalex77** [comment]
@phiresky It would be great if you can make a new minor release, so I can finish with the Homebrew formula.

**Comment by phiresky** [comment]
@filalex77  i've released a new minor version

**Comment by AlJohri** [comment]
thanks! can you update the macOS instructions in the readme
