### ISSUE TITLE
Windows tests are failing

### ISSUE THREAD

**Issue by TriplEight** [phiresky/ripgrep-all#94]
`win-msvc` test fails with https://github.com/phiresky/ripgrep-all/runs/1621230957#step:11:241
`win-gnu` build fails with https://github.com/phiresky/ripgrep-all/pull/92/checks?check_run_id=1625639166#step:9:566

_Originally posted by @TriplEight in https://github.com/phiresky/ripgrep-all/issues/92#issuecomment-752409159_

The required CI changes to run these tests can be found in the commits to the above PR ^

**Comment by phiresky** [comment]
Seems fixed
