### ISSUE TITLE
Question: how to increase rga speed on large library of pdfs?

### ISSUE THREAD

**Issue by nettoyoussef** [phiresky/ripgrep-all#95]
Hi. Thanks for the awesome effort put into this package.

Currently, I am trying to migrate from Recoll to ripgrep-all, since it seems better integrated with emacs (emacs has a large suite of tools for cli search).

However, due to conversion failures, `ripgrep-all` seems to be very slow compared to Recoll, in part due to a much smaller cache.
Is there anything that I can do to make `rga` faster?

Searching in a large ebooks folder (around 51 gb and 6.000 objects), these are the results from `rga`:

```sh
# with cache
rga -l -g "*.{pdf, epub}" "gibrat" ~/zotero_articles  235.59s user 19.29s system 263% cpu 1:36.83 total
 ```
The `rga` cache is about 966Mb, while the Recoll index is about 9gb (10x difference).

However, Recoll is much faster:

```sh
time recoll -c ~/.recoll/zotero -t -q gibrat  0.13s user 0.02s system 99% cpu 0.153 total
```
It may be argued that Recoll is doing less work since it does not return the context of each search,
so below you will also find a comparison with the list of results passed to the gui (time is approximated
since one must exit the gui for the clock to stop):

```sh
time recoll -c ~/.recoll/zotero -q gibrat  0.92s user 0.04s system 47% cpu 2.018 total
```

Other interfaces and conversions that depend on pdf extraction are much slower.
I post them here just for comparison:

```sh
time recoll -c ~/.recoll/zotero -b -t -q gibrat | sed 's,file://,,g' | xargs -d"\n" pdfgrep -H -i "gibrat" 509.94s user 11.63s system 99% cpu 8:44.63 total
```
Here, of course, the main problem is with pdfgrep, which is very slow.
Then, we can use `pdftotext`, which is arguably faster.
We have to use a loop which is better expressed in a bash script:

```bash
#!/bin/bash
IFS=$'\n'
for f in $(recoll -c ~/.recoll/zotero -b -t -q $@ | sed 's,file://,,g'); do
  pdftotext -q "$f" - | rg -S $@
done
unset IFS
```

Since `pdftotext` is around 2 times faster (according to #31) than `pdfgrep`, our time is reduced to half.

```sh
time  ./recoll.sh gibrat  267.65s user 9.64s system 100% cpu 4:35.42 total
```

I could not yet use the Recoll Python API, but I expect results at least better than the GUI and close to the ones
for filenames only.

**Comment by phiresky** [comment]
rga's caching purely has the function of caching the extraction part. The search is still a "naive" but extremely optimized full text search with rg. This is usually very fast and often even faster than using whatever "smart" indexing techniques may be used by other software. But at some point using a "real" full text search engine is going to be faster.

I'd expect rga to scan through data at a rate of around 100MB/s to 1GB/s (of raw plain text - after extraction).

There is a default limit to the size of extracted content that will be cached which can be increased with e.g. `--rga-cache-max-blob-len=10M`. If the files are all in cache and the query is still slower than alternate software then probably more sophisticated software is going to be better.
