### ISSUE TITLE
Build fails on Apple Silicon (aarch64-apple-darwin)

### ISSUE THREAD

**Issue by richiksc** [phiresky/ripgrep-all#96]
Homebrew is trying to get all its Rust formulae to build natively on ARM Macs (https://github.com/Homebrew/homebrew-core/issues/68301), and currently, `ripgrep-all` v0.9.6 is failing to build.

Homebrew is building `0.9.6` via `cargo install --locked`.

Looks like the issue is with a dependency, `lmdb-rkv-sys`, which uses an outdated version of the `cc` crate, which is actually a dependency of the `rkv` crate. I'll open an issue with them, and after that, the dependency would need to be updated for this project. It would be great if you could keep this open as a tracking issue if any other issues come up after `lmdb-rkv-sys` and `rkv` are updated, just so we can follow up on any further issues that arise.

Current build error:

```
The following warnings were emitted during compilation:

warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch
warning: error: unknown target triple 'unknown-apple-macosx11.0.0', please use -triple or -arch

error: failed to run custom build command for `lmdb-rkv-sys v0.11.0`

Caused by:
  process didn't exit successfully: `/private/tmp/ripgrep-all-20210108-20170-1y2jt66/ripgrep-all-0.9.6/target/release/build/lmdb-rkv-sys-664251cca3dc46db/build-script-build` (exit code: 1)
```

**Comment by richiksc** [comment]
Looks like `lmdb-rkv-sys` doesn't actually pin a specific version of `cc`, and `ripgrep-all` builds successfully on `master`, which uses `cc` v1.0.59 in `Cargo.lock`, which has a partial fix. However, I recommend updating to the latest version of `cc` since the issue was fully fixed in `cc` 1.0.60. I'll open a PR to update Cargo.lock, and then if you can cut a new point release, we should be golden!

**Comment by richiksc** [comment]
@phiresky I've opened #97 that should fix the build on arm64 macOS, and then Homebrew would need a new version to be tagged.

**Comment by richiksc** [comment]
@carlocab Just saw that you added a patch for Cargo.lock for `angle-grinder` without requiring a new release. Could the same be done for `ripgrep-all`?

**Comment by carlocab** [comment]
Yes. Just pattern it after `angle-grinder`. Ping me when you open the PR so I can add the CI-force-arm flag.

**Comment by richiksc** [comment]
@phiresky, v0.9.6 fails to build even with the Cargo.lock patch from #97 due to the fact that `cachedir` crate v0.1.1 is no longer available on crates.io. cachedir 0.2+ is a completely different create. It looks like you've removed the dependency on `cachedir` in master, do you know when you're planning on cutting a new release?

**Comment by frewsxcv** [comment]
> @phiresky, v0.9.6 fails to build even with the Cargo.lock patch from #97 due to the fact that `cachedir` crate v0.1.1 is no longer available on crates.io. cachedir 0.2+ is a completely different create. It looks like you've removed the dependency on `cachedir` in master, do you know when you're planning on cutting a new release?

If anyone runs into this, you can work around it by installing ripgrep-all from the `master` branch of the repo:

```
cargo install ripgrep_all --git https://github.com/phiresky/ripgrep-all.git
```

**Comment by richiksc** [comment]
@frewsxcv Yes, we know it builds successfully on master, but Homebrew requires a tagged release to publish a bottle.

**Comment by RunningIkkyu** [comment]
This works for me (on Apple m1):

```bash
brew install --build-from-source ripgrep-all
```

And if you're using rag with fzf, need to change `xdg-open` to `open`, add this to `.bashrc`/`.zshrc`

```
rga-fzf() {
    RG_PREFIX="rga --files-with-matches"
    local file
    file="$(
    FZF_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
      fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
        --phony -q "$1" \
        --bind "change:reload:$RG_PREFIX {q}" \
        --preview-window="70%:wrap"
    )" &&
    echo "opening $file" &&
    open "$file"
}
```

**Comment by carlocab** [comment]
ripgrep-all was bottled about three weeks ago in https://github.com/Homebrew/homebrew-core/commit/6fea4cfbfdbd84feac10467d5257154cebe8f98c, so there should be no need to build this from source.

**Comment by phiresky** [comment]
0.10 removes the lmdb which should remove this issue if it was still present
