### ISSUE TITLE
pandoc: unrecognized option `--wrap=none

### ISSUE THREAD

**Issue by wzhsh90** [phiresky/ripgrep-all#98]
[root@izwz9594gzu20j2z7lneucz rga]# ./rga "中" /opt/test/
/opt/test/test.docx: preprocessor command failed: '"/opt/rga/rga-preproc" "/opt/test/test.docx"': 
-------------------------------------------------------------------------------
adapter: pandoc
pandoc: unrecognized option `--wrap=none'
Try pandoc --help for more information.
Error: subprocess failed: ExitStatus(ExitStatus(512))
-------------------------------------------------------------------------------

os:centos7.6

I use the ripgrep_all-v0.9.6-x86_64-unknown-linux-musl.tar.gz.

**Comment by phiresky** [comment]
Your pandoc version is too old
