### ISSUE TITLE
Opening a xml file and ran code inside when it wasn't supposed to (security?)

### ISSUE THREAD

**Issue by christalib** [phiresky/ripgrep-all#99]
I used rga-fzf to search for a xml file. That file had a powershell script in it. When clicking on enter to open the file, the powershell script got executed which wasn't intended as it was malicious 😅 

I am using Manjaro (Arch Linux) with zsh and powershell+wine installed. 

Did anyone else observed that?

Some screenshots: 

![Screenshot from 2021-01-25 13-10-27](https://user-images.githubusercontent.com/3540752/105704511-35ff3d00-5f0f-11eb-9675-bf50c44e9c81.png)
![Screenshot from 2021-01-25 13-10-44](https://user-images.githubusercontent.com/3540752/105704523-3a2b5a80-5f0f-11eb-9a4d-bebbe5cb5e6d.png)

**Comment by christalib** [comment]
This behaviour seems to come from using `xdg-open` to open file.

**Comment by phiresky** [comment]
Huh. Are you sure it's actually running some powershell script? Maybe you just have wine notepad or something associated with xml files? What happens if you run `xdg-open yourxmlfile.xml`?

**Comment by phiresky** [comment]
yeah from your `ps` screenshot it seems like it executed `wine start /ProgIDOpen xmlfile ...../foo.evtx.xml`. So seems like expected behaviour to me: your xdg settings seem to have winebrowser set as the default program for xml files.

For example, I have the following file in `~/.local/share/applications/wine-extension-xml.desktop`:

```ini
Desktop Entry]
Type=Application
Name=winebrowser
MimeType=application/xml;
Exec=env WINEPREFIX="~/.wine" wine start /ProgIDOpen xmlfile %f
NoDisplay=true
StartupNotify=true
Icon=7765_winebrowser.0
```

**Comment by christalib** [comment]
Hi! Thank you for the quick answer!

Yeah, it seems to come from the wine configuration. I followed the tips in the archlinux wiki you sent and that seems to do the trick. The mentioned behaviour isn't showing up anymore. 

Thank you! I'll close this issue. I love your tool, keep up the good work!

**Comment by rickhg12hs** [comment]
Is there a `firejail` configuration that could protect against this?
